# Generated by Django 4.2.7 on 2023-11-27 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_document', models.FileField(blank=True, null=True, upload_to='documents')),
                ('status', models.CharField(choices=[('altered', 'Altered'), ('approved', 'Approved'), ('not_checked', 'Not checked'), ('need_correction', 'Need correction')], default='not_checked', max_length=20)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
