# Generated by Django 4.2.7 on 2023-11-27 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcategorydocumenttype',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_category', to='documents.documenttype', verbose_name='Related File Type'),
        ),
        migrations.AddField(
            model_name='applicationcategory',
            name='document_types',
            field=models.ManyToManyField(through='applications.ApplicationCategoryDocumentType', to='documents.documenttype'),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.applicationcategory'),
        ),
        migrations.AddField(
            model_name='application',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applications.applicationperiod'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationcategorydocumenttype',
            unique_together={('application_category', 'document_type')},
        ),
    ]
