# Generated by Django 4.2.7 on 2023-11-27 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='period',
        ),
        migrations.AddField(
            model_name='applicationcategory',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applications.applicationperiod'),
        ),
    ]
